name: Automatically create PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Create PR with changes
          base: main
          branch: ${{ github.ref }}
          assignees: kec0130
          title: BLOG POST UPDATE
          body: pr 생성 자동화 테스트
